import java.time.LocalDateTime

job('First_maven_spring_rest_via_dsl') {
    description("Spring Boot Rest full generated by DSL on ${LocalDateTime.now()}, a small maven spring rest project")
    scm {
        git('https://github.com/sabzarar/springprojects.git', 'master')
    }

    triggers {
        scm ('* * * * *')
    }

    steps {
        maven('clean package', 'springrest-demo/pom.xml')
    }

    publishers {
        archiveArtifacts '**/springrest-demo*.war'
    }

}