pipeline {
    agent any
	stages {
        stage('Init') {
            steps {
                echo 'Hi, This is Sabzar from Evry Tieto. Wellcome to Jenkins PipeLine'
                echo 'Initializing the project'
		    }
		}	
        stage('build') {
            steps {
                echo 'Building sample maven project'
				bat 'mvn clean package -f java-tomcat-sample/pom.xml'
            }
			 post {
                success {
                    echo "Now Archiving the Artifacts...."
                    archiveArtifacts artifacts: '**/*.war'
                }
            }
			
        }
		stage('Integration Testing') {
            steps {
                echo 'Intehration Testing'
				echo 'All test cases passes'
            }
        }
        stage('deploy') {
            steps {
                echo 'Deploying the project to stage'
            }
        }
		stage('deploy Prodection') {
            steps {
                echo 'Deploying the project to Prodection'
            }
        }

    }
}