pipeline {
    agent any
	stages {
        stage('Init') {
            steps {
                echo 'Hi, This is Sabzar from Evry Tieto. Wellcome to Jenkins PipeLine'
                echo 'Initializing the project'
		    }
		}	
        stage('build') {
            steps {
                echo 'Building sample maven project'
				bat 'mvn clean package -f java-tomcat-sample/pom.xml'
            }
			 post {
                success {
                    echo "Now Archiving the Artifacts...."
                    archiveArtifacts artifacts: '**/*.war'
                }
            }
			
        }
		stage('Integration Testing') {
            steps {
                echo 'Intehration Testing'
				echo 'All test cases passes'
            }
        }
        stage('deploy') {
            steps {
		        echo 'Deploying the project to stage'
				build job: 'Deploy_Application_Staging_Env_From_Code_PipeLine'
            }
        }
		stage('deploy Prodection') {
            steps {
			    timeout(time:5, unit:'DAYS'){
				input message: 'Aprove for Prodection Deployment'
		
				}
                echo 'Deploying the project to Prodection'
				echo 'call build job: here'
            }
        }

    }
}